#!/usr/bin/env bash
#
# Create a new Jekyll post with name $1 and fill in the frontmatter.
#

if [ -z "$1" ]; then
    post_name="New post"
else
    post_name="$@"
fi

# get shell-friendly version of $post_name (thx me for ezstring)
file_name="$(date "+%Y-%m-%d")-$(ezstring "$post_name").md"

echo \
"---
title: $post_name
---

" >> "$file_name"

# bring it up for editing
$EDITOR "$file_name"
