#!/usr/bin/env bash
#
# Create a new Jekyll post with name $1 and fill in the frontmatter.
#

if [ -z "$1" ]; then
    title="New post"
else
    title="$@"
fi

# get shell-friendly version of $post_name (thx me for ezstring)
filename="$(date "+%Y-%m-%d")-$(ezstring "$title").md"

# insert template
# Jekyll will won't read the title if it has a colon in it, since YAML
# uses them for variable definitions or something. You can fix that by
# enclosing the title in quotes (e.g. title: "Colons: they break
# things"). However, since that seems to be the only thing YAML gets
# unhappy about, I don't wrap the title in the template.
echo \
"---
title: $title
---

" >> "$filename"

# bring it up for editing
$EDITOR "$filename"
