#!/usr/bin/env bash
#
# Create a new Jekyll post with name $1 and fill in the frontmatter.
#

layout="post"

if [ -z "$1" ]; then
    post_name="New post"
else
    post_name="$@"
fi

# filename takes the shell-friendly version of $post_name (thx me for ezpath)
file_name="$(date "+%Y-%m-%d")-$(ezpath -s "$post_name").md"

echo "---
layout: $layout
title: \"$post_name\"
date:
---

" > "$file_name"

# run my update script on it to fill in datetime
update "$file_name"

# bring it up for editing
$EDITOR "$file_name"
